version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=arc-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
  web:
    image: nginx
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db
